import { uid } from 'quasar'

const fields = [
	{
		id: uid(),
		text: 'Операторы',
		hidden: false,
		open: true,
		type: 0,
		selected: false,
		drag: false,
		children: [
			{ id: uid(), text: 'И', hidden: false, type: 0, selected: false, drag: true, drop: true },
			{
				id: uid(),
				text: 'ИЛИ',
				hidden: false,
				type: 0,
				typ: true,
				selected: false,
				drag: true,
				drop: true,
			},
		],
	},
	{
		id: uid(),
		text: 'Тип карточки',
		hidden: false,
		open: true,
		type: 1,
		selected: false,
		drag: false,
		children: [
			{
				id: uid(),
				text: 'Документ',
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				drop: false,
				children: [
					{ type: 1, id: uid(), text: 'Заявка', hidden: false, selected: false, drag: true },
					{ type: 1, id: uid(), text: 'Договор', hidden: false, selected: false, drag: true },
					{ type: 1, id: uid(), text: 'Письмо', hidden: false, selected: false, drag: true },
					{ type: 1, id: uid(), text: 'Входящий', hidden: false, selected: false, drag: true },
					{ type: 1, id: uid(), text: 'Исходящий', hidden: false, selected: false, drag: true },
					{ type: 1, id: uid(), text: 'Приказ', hidden: false, selected: false, drag: true },
					{ type: 1, id: uid(), text: 'Заявление', hidden: false, selected: false, drag: true },
					{ type: 1, id: uid(), text: 'Письмо', hidden: false, selected: false, drag: true },
					{ type: 1, id: uid(), text: 'Черновик', hidden: false, selected: false, drag: true },
				],
			},
			{
				id: uid(),
				text: 'Задание',
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				children: [
					{ id: uid(), text: 'Тема', hidden: false, type: 1, selected: false, drag: true },
					{
						id: uid(),
						text: 'Дата завершения плановая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Дата завершения плановая до переносов',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Дата завершения фактическая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{ id: uid(), text: 'Дата контроля', hidden: false, type: 1, selected: false, drag: true },
					{
						id: uid(),
						text: 'Дата напоминания',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Дата начала плановая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Дата начала плановая до переносов',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Дата начала фактическая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{ id: uid(), text: 'Дата отправки', hidden: false, type: 1, selected: false, drag: true },
					{ id: uid(), text: 'Важность', hidden: false, type: 1, selected: false, drag: true },
					{
						id: uid(),
						text: 'Автор',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						children: [
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Фамилия', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Имя', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Отчество', drag: true },
							{
								type: 2,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Дата рождения',
								drag: true,
							},
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Должность', drag: true },
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Руководитель',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Местный телефон',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Домашний телефон',
								drag: true,
							},
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Факс', drag: true },
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Номер паспорта',
								drag: true,
							},
							{
								type: 2,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Паспорт выдан',
								drag: true,
							},
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Комната', drag: true },
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Сотовый телефон',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'IP телефон',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Значимость',
								drag: true,
							},
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Email', drag: true },
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Организация',
								drag: true,
							},
							{
								type: 5,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Является руководителем',
								drag: true,
							},
						],
					},
					{ id: uid(), text: 'Содержание ', hidden: false, type: 1, selected: false, drag: true },
					{ id: uid(), text: 'Документ', hidden: false, type: 1, selected: false, drag: true },
					{ id: uid(), text: 'Исполнители', hidden: false, type: 1, selected: false, drag: true },
					{ id: uid(), text: 'Состояние ', hidden: false, type: 1, selected: false, drag: true },
					{
						id: uid(),
						text: 'Подчиненные группы заданий',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Подчиненные задания',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Контролер',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						children: [
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Фамилия', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Имя', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Отчество', drag: true },
							{
								type: 2,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Дата рождения',
								drag: true,
							},
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Должность', drag: true },
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Руководитель',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Местный телефон',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Домашний телефон',
								drag: true,
							},
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Факс', drag: true },
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Номер паспорта',
								drag: true,
							},
							{
								type: 2,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Паспорт выдан',
								drag: true,
							},
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Комната', drag: true },
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Сотовый телефон',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'IP телефон',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Значимость',
								drag: true,
							},
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Email', drag: true },
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Организация',
								drag: true,
							},
							{
								type: 5,
								hidden: false,
								selected: false,
								id: uid(),
								text: 'Является руководителем',
								drag: true,
							},
						],
					},
					{
						id: uid(),
						text: 'Вид контроля',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						children: [
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Option 1', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Option 2', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Option 3', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Option 4', drag: true },
						],
					},
					{
						id: uid(),
						text: 'Делегат',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						children: [
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Option 1', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Option 2', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Option 3', drag: true },
							{ type: 1, hidden: false, selected: false, id: uid(), text: 'Option 4', drag: true },
						],
					},
					{
						id: uid(),
						text: 'Длительность фактическая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Завершено позже срока',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Задание ответственного исполнителя',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						text: 'Запрошенный срок',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
				],
			},
			{
				id: uid(),
				text: 'Группа заданий',
				hidden: false,
				type: 1,
				selected: false,
				drag: false,
				children: [
					{ id: uid(), text: 'Тема', type: 1, hidden: false, selected: false, drag: true },
					{ id: uid(), text: 'Отправлено', type: 1, hidden: false, selected: false, drag: true },
					{
						id: uid(),
						text: 'Срок исполнения',
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{ id: uid(), text: 'Автор', type: 1, hidden: false, selected: false, drag: true },
					{ id: uid(), text: 'Содержание ', type: 1, hidden: false, selected: false, drag: true },
					{ id: uid(), text: 'Документ', type: 1, hidden: false, selected: false, drag: true },
					{ id: uid(), text: 'Исполнители', type: 1, hidden: false, selected: false, drag: true },
					{ id: uid(), text: 'Состояние ', type: 1, hidden: false, selected: false, drag: true },
					{
						id: uid(),
						text: 'Подчиненные задания',
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{ id: uid(), text: 'Контролер', type: 1, hidden: false, selected: false, drag: true },
					{ id: uid(), text: 'Тип', type: 1, hidden: false, selected: false, drag: true },
				],
			},
		],
	},
]

export { fields }
