import { uid } from 'quasar'
enum Kind {
	String,
	Text,
	Date,
	Org,
	Num,
	Man,
	Status,
	Link,
	Phone,
	Email,
	Bool,
}
const operators = [
	{
		id: '1',
		text: 'И',
		hidden: false,
		type: 0,
		selected: false,
		drag: true,
		drop: true,
		icon: 'mdi-gate-and'
	},
	{
		id: '2',
		text: 'ИЛИ',
		hidden: false,
		type: 0,
		typ: true,
		selected: false,
		drag: true,
		drop: true,
		icon: 'mdi-gate-and'
	},
]
const fields = [
	{
		id: 'type',
		text: 'Тип карточки',
		hidden: false,
		open: true,
		type: 1,
		selected: false,
		drag: false,
		children: [
			{
				id: uid(),
				text: 'Документ',
				hidden: false,
				type: 1,
				selected: false,
				drag: false,
				drop: false,
				open: true,
				children: [
					{
						id: uid(),
						parents: ['Документ'],
						text: 'Тема',
						type: 1,
						hidden: false,
						open: true,
						selected: false,
						drag: true,
						drop: false,
						kind: Kind.String,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ'],
						text: 'Номер',
						kind: Kind.Num,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ'],
						text: 'Регистратор',
						kind: Kind.Man,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ'],
						text: 'Содержание',
						kind: Kind.Text,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ'],
						text: 'Дата документа',
						kind: Kind.Date,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					// doc begin ************************
					{
						type: 1,
						id: uid(),
						parents: ['Документ'],
						text: 'Договор',
						hidden: false,
						selected: false,
						drag: false,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Номер',
								kind: Kind.Num,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Дата регистрации',
								kind: Kind.Date,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								date: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Регистратор',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Подготовил',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Предмет договора',
								kind: Kind.Text,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Организация',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Дата документа',
								kind: Kind.Date,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								date: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Ответственный',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Подписывают',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Организация контрагент',
								kind: Kind.Org,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
								children: [
									{
										id: uid(),
										parents: ['Документ', 'Договор', 'Организация контрагент'],
										text: 'Контактное лицо',
										kind: Kind.Man,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Договор', 'Организация контрагент'],
										text: 'Организация',
										kind: Kind.Org,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Договор', 'Организация контрагент'],
										text: 'Телефон',
										kind: Kind.Phone,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Договор', 'Организация контрагент'],
										text: 'Email',
										kind: Kind.Email,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Договор', 'Организация контрагент'],
										text: 'ИНН',
										kind: Kind.String,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: false,
									},
									{
										id: uid(),
										parents: ['Документ', 'Договор', 'Организация контрагент'],
										text: 'ОГРН',
										kind: Kind.String,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: false,
									},
									{
										id: uid(),
										parents: ['Документ', 'Договор', 'Организация контрагент'],
										text: 'БИК',
										kind: Kind.String,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: false,
									},
								],
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Состояние',
								kind: Kind.Status,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Заданиe',
								kind: Kind.Link,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор'],
								text: 'Группа заданий',
								kind: Kind.Link,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
						],
					},

					{
						type: 1,
						id: uid(),
						parents: ['Документ'],
						text: 'Исходящий',
						hidden: false,
						selected: false,
						drag: false,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Тема',
								kind: Kind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Номер',
								kind: Kind.Num,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Дата регистрации',
								kind: Kind.Date,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								date: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Регистратор',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Подготовил',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Содержание',
								kind: Kind.Text,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Согласующие',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Подписывают',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Получатели',
								kind: Kind.Org,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
								children: [
									{
										id: uid(),
										parents: ['Документ', 'Исходящий', 'Получатели'],
										text: 'Контактное лицо',
										kind: Kind.Man,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Исходящий', 'Получатели'],
										text: 'Организация',
										kind: Kind.Org,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Исходящий', 'Получатели'],
										text: 'Телефон',
										kind: Kind.Phone,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Исходящий', 'Получатели'],
										text: 'Email',
										kind: Kind.Email,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
								],
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Состояние',
								kind: Kind.Status,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Заданиe',
								kind: Kind.Link,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий'],
								text: 'Группа заданий',
								kind: Kind.Link,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
						],
					},
					{
						type: 1,
						id: uid(),
						parents: ['Документ'],
						text: 'Входящий',
						hidden: false,
						selected: false,
						drag: false,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Тема',
								kind: Kind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Номер',
								kind: Kind.Num,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Дата регистрации',
								kind: Kind.Date,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								date: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Регистратор',
								kind: Kind.Man,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Содержание',
								kind: Kind.Text,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Исх.номер',
								kind: Kind.Num,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Дата документа',
								kind: Kind.Date,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Отправитель',
								kind: Kind.Org,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
								children: [
									{
										id: uid(),
										parents: ['Документ', 'Входящий', 'Отправитель'],
										text: 'Контактное лицо',
										kind: Kind.Man,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Входящий', 'Отправитель'],
										text: 'Организация',
										kind: Kind.Org,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Входящий', 'Отправитель'],
										text: 'Телефон',
										kind: Kind.Phone,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
									{
										id: uid(),
										parents: ['Документ', 'Входящий', 'Отправитель'],
										text: 'Email',
										kind: Kind.Email,
										type: 1,
										hidden: false,
										selected: false,
										drag: true,
										man: true,
									},
								],
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Состояние',
								kind: Kind.Status,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Заданиe',
								kind: Kind.Link,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий'],
								text: 'Группа заданий',
								kind: Kind.Link,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
						],
					},
				],
			},
			{
				id: uid(),
				text: 'Задание',
				hidden: false,
				type: 1,
				selected: false,
				drag: false,
				children: [
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Название',
						kind: Kind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Дата контроля',
						kind: Kind.Date,
						date: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Дата отправки',
						kind: Kind.Date,
						date: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Важность',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Автор',
						kind: Kind.Man,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Фамилия',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Имя',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Отчество',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Дата рождения',
								kind: Kind.Date,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Должность',
								kind: Kind.Text,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Руководитель',
								kind: Kind.Bool,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Местный телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Домашний телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Факс',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Номер паспорта',
								kind: Kind.Text,
								drag: true,
								inp: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Паспорт выдан',
								kind: Kind.Text,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Комната',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Сотовый телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'IP телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Email',
								kind: Kind.Email,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Организация',
								kind: Kind.Org,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Автор'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Содержание',
						kind: Kind.Text,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Докумeнт',
						kind: Kind.Link,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Исполнители',
						kind: Kind.Man,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Состояние ',
						kind: Kind.Status,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Подчиненные группы заданий',
						kind: Kind.Link,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Контролер',
						kind: Kind.Man,
						man: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Фамилия',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Имя',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Отчество',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Дата рождения',
								kind: Kind.Text,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Должность',
								kind: Kind.Text,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Руководитель',
								kind: Kind.Man,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Email',
								kind: Kind.Email,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Организация',
								kind: Kind.Org,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'На исполнение', 'Контролер'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Длительность фактическая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Завершено позже срока',
						kind: Kind.Bool,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						ruk: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Задание ответственного исполнителя',
						kind: Kind.Bool,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание'],
						text: 'На исполнение',
						hidden: false,
						type: 1,
						selected: false,
						drag: false,
						children: [
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Название',
								kind: Kind.String,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Срок исполнения',
								kind: Kind.Date,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								date: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Дата контроля',
								kind: Kind.Date,
								date: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Дата отправки',
								kind: Kind.Date,
								date: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Важность',
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Автор',
								kind: Kind.Man,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								man: true,
								children: [
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Фамилия',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Имя',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Отчество',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Дата рождения',
										kind: Kind.Date,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Должность',
										kind: Kind.Text,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Руководитель',
										kind: Kind.Bool,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Местный телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Домашний телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Факс',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Номер паспорта',
										kind: Kind.Text,
										drag: true,
										inp: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Паспорт выдан',
										kind: Kind.Text,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Комната',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Сотовый телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'IP телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Значимость',
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Email',
										kind: Kind.Email,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Организация',
										kind: Kind.Org,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Автор'],
										text: 'Является руководителем',
										kind: Kind.Bool,
										drag: true,
										ruk: true,
									},
								],
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Содержание',
								kind: Kind.Text,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Докумeнт',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Исполнители',
								kind: Kind.Man,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Состояние ',
								kind: Kind.Status,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Подчиненные группы заданий',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Подчиненные задания',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Контролер',
								kind: Kind.Man,
								man: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								children: [
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Фамилия',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Имя',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Отчество',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Дата рождения',
										kind: Kind.Text,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Должность',
										kind: Kind.Text,
										man: true,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Руководитель',
										kind: Kind.Man,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Значимость',
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Email',
										kind: Kind.Email,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Организация',
										kind: Kind.Org,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На исполнение', 'Контролер'],
										text: 'Является руководителем',
										kind: Kind.Bool,
										drag: true,
										ruk: true,
									},
								],
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Длительность фактическая',
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Завершено позже срока',
								kind: Kind.Bool,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								ruk: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На исполнение'],
								text: 'Задание ответственного исполнителя',
								kind: Kind.Bool,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание'],
						text: 'На ознакомление',
						hidden: false,
						type: 1,
						selected: false,
						drag: false,
						children: [
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Название',
								kind: Kind.String,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Срок исполнения',
								kind: Kind.Date,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								date: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Дата контроля',
								kind: Kind.Date,
								date: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Дата отправки',
								kind: Kind.Date,
								date: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Важность',
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Автор',
								kind: Kind.Man,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								man: true,
								children: [
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Фамилия',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Имя',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Отчество',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Дата рождения',
										kind: Kind.Date,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Должность',
										kind: Kind.Text,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Руководитель',
										kind: Kind.Bool,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Местный телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Домашний телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Факс',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Номер паспорта',
										kind: Kind.Text,
										drag: true,
										inp: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Паспорт выдан',
										kind: Kind.Text,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Комната',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Сотовый телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'IP телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Значимость',
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Email',
										kind: Kind.Email,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Ор��анизация',
										kind: Kind.Org,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Автор'],
										text: 'Является руководителем',
										kind: Kind.Bool,
										drag: true,
										ruk: true,
									},
								],
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Содержание',
								kind: Kind.Text,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Докумeнт',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Исполнители',
								kind: Kind.Man,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Состояние ',
								kind: Kind.Status,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Подчиненные группы заданий',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Подчиненные задания',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Контролер',
								kind: Kind.Man,
								man: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								children: [
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Фамилия',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Имя',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Отчество',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Дата рождения',
										kind: Kind.Text,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Должность',
										kind: Kind.Text,
										man: true,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Руководитель',
										kind: Kind.Man,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Значимость',
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Email',
										kind: Kind.Email,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Организация',
										kind: Kind.Org,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На ознакомление', 'Контролер'],
										text: 'Является руководителем',
										kind: Kind.Bool,
										drag: true,
										ruk: true,
									},
								],
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Длительность фактическая',
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На ознакомление'],
								text: 'Завершено позже срока',
								kind: Kind.Bool,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание'],
						text: 'На согласование',
						hidden: false,
						type: 1,
						selected: false,
						drag: false,
						children: [
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Название',
								kind: Kind.String,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Срок исполнения',
								kind: Kind.Date,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								date: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Дата контроля',
								kind: Kind.Date,
								date: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Дата отправки',
								kind: Kind.Date,
								date: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Важность',
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Автор',
								kind: Kind.Man,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								man: true,
								children: [
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Фамилия',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Имя',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Отчество',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Дата рождения',
										kind: Kind.Date,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Должность',
										kind: Kind.Text,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Руководитель',
										kind: Kind.Bool,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Местный телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Домашний телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Факс',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Номер паспорта',
										kind: Kind.Text,
										drag: true,
										inp: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Паспорт выдан',
										kind: Kind.Text,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Комната',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласован����', 'Автор'],
										text: 'Сотовый телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'IP телефон',
										kind: Kind.Phone,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Значимость',
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Email',
										kind: Kind.Email,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Организация',
										kind: Kind.Org,
										drag: true,
										man: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Автор'],
										text: 'Является руководителем',
										kind: Kind.Bool,
										drag: true,
										ruk: true,
									},
								],
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Содержание',
								kind: Kind.Text,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								inp: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Докумeнт',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Исполнители',
								kind: Kind.Man,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Состояние ',
								kind: Kind.Status,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Подчиненные группы заданий',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Подчиненные задания',
								kind: Kind.Link,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Контролер',
								kind: Kind.Man,
								man: true,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								children: [
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Фамилия',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Имя',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Отчество',
										kind: Kind.Text,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Дата рождения',
										kind: Kind.Text,
										drag: true,
										date: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Должность',
										kind: Kind.Text,
										man: true,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Руководитель',
										kind: Kind.Man,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Значимость',
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Email',
										kind: Kind.Email,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Организация',
										kind: Kind.Org,
										drag: true,
									},
									{
										type: 1,
										hidden: false,
										selected: false,
										id: uid(),
										parents: ['Задание', 'На согласование', 'Контролер'],
										text: 'Является руководителем',
										kind: Kind.Bool,
										drag: true,
										ruk: true,
									},
								],
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Длительность фактическая',
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Завершено позже срока',
								kind: Kind.Bool,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								ruk: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Задание ответственного исполнителя',
								kind: Kind.Bool,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Инициатор',
								kind: Kind.Man,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Этап согласования',
								kind: Kind.String,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Задание', 'На согласование'],
								text: 'Цикл согласования',
								kind: Kind.Num,
								hidden: false,
								type: 1,
								selected: false,
								drag: true,
							},
						],
					},
				],
			},
			{
				id: uid(),
				text: 'Группа заданий',
				hidden: false,
				type: 1,
				selected: false,
				drag: false,
				children: [
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Тема',
						kind: Kind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Отправлено',
						kind: Kind.Date,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Автор',
						kind: Kind.Man,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Фамилия',
								kind: Kind.Text,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Имя',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Отчество',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Дата рождения',
								kind: Kind.Text,
								date: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Должность',
								kind: Kind.Text,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Руководитель',
								kind: Kind.Man,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Местный телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Домашний телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Факс',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Номер паспорта',
								kind: Kind.Text,
								drag: true,
								inp: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Паспорт выдан',
								kind: Kind.Text,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Комната',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Сотовый телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'IP телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Email',
								kind: Kind.Email,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Организация',
								kind: Kind.Org,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Автор'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Содержание ',
						kind: Kind.Text,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Докумeнт',
						kind: Kind.Link,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Исполнители',
						kind: Kind.Man,
						man: true,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Состояние ',
						kind: Kind.Status,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Контролер',
						kind: Kind.Man,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Фамилия',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Имя',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Отчество',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Дата рождения',
								kind: Kind.Date,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Должность',
								kind: Kind.Text,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Руководитель',
								kind: Kind.Man,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Местный телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Домашний телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Факс',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Номер паспорта',
								kind: Kind.Text,
								drag: true,
								inp: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Паспорт выдан',
								kind: Kind.Text,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Комната',
								kind: Kind.Text,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Сотовый телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'IP телефон',
								kind: Kind.Phone,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Email',
								kind: Kind.Email,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Организация',
								kind: Kind.Org,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['ГЗ', 'Контролер'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['ГЗ'],
						text: 'Тип',
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
				],
			},
		],
	},
]

export { fields, operators }
