import { uid } from 'quasar'

enum Kind {
	String,
	Text,
	Date,
	Org,
	Num,
	Man,
	Status,
	Link,
	Phone,
	Email,
	Bool,
}
const zero = [
	{
		id: uid(),
		text: 'Документы',
		value: 'Документы',
		selected: false,
		level: 0,
		parent: [],
		children: [
			{
				id: uid(),
				text: 'Исходящий',
				value: 'Исходящий',
				selected: false,
				parent: ['Документы'],
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Входящий',
				value: 'Входящий',
				selected: false,
				parent: ['Документы'],
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Договор',
				value: 'Договор',
				selected: false,
				parent: ['Документы'],
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Доп.соглашение',
				value: 'Доп.соглашение',
				selected: false,
				parent: ['Документы'],
				level: 1,
				children: [],
			},
		],
	},
	{
		id: uid(),
		text: 'Задания',
		value: 'Задания',
		selected: false,
		level: 0,
		parent: [],
		children: [
			{
				id: uid(),
				text: 'На исполнение',
				value: 'На исполнение',
				selected: false,
				parent: ['Задания'],
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'На ознакомление',
				value: 'На ознакомление',
				selected: false,
				parent: ['Задания'],
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'На согласование',
				value: 'На согласование',
				selected: false,
				parent: ['Задания'],
				level: 1,
				children: [],
			},
		],
	},
	{
		id: uid(),
		text: 'Группа заданий',
		value: 'Группа заданий',
		selected: false,
		level: 0,
		parent: [],
		children: [
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Тема',
				kind: Kind.String,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
				inp: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Отправлено',
				kind: Kind.Date,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Срок исполнения',
				kind: Kind.Date,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Автор',
				kind: Kind.Man,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
				man: true,
				children: [
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Фамилия',
						kind: Kind.Text,
						man: true,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Имя',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Отчество',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Дата рождения',
						kind: Kind.Text,
						date: true,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Должность',
						kind: Kind.Text,
						drag: true,
						man: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Руководитель',
						kind: Kind.Man,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Местный телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Домашний телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Факс',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Номер паспорта',
						kind: Kind.Text,
						drag: true,
						inp: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Паспорт выдан',
						kind: Kind.Text,
						drag: true,
						date: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Комната',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Сотовый телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'IP телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Значимость',
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Email',
						kind: Kind.Email,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Организация',
						kind: Kind.Org,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						drag: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Содержание ',
				kind: Kind.Text,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
				inp: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Докумeнт',
				kind: Kind.Link,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Исполнители',
				kind: Kind.Man,
				man: true,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Состояние ',
				kind: Kind.Status,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Подчиненные задания',
				kind: Kind.Link,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Контролер',
				kind: Kind.Man,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
				man: true,
				children: [
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Фамилия',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Имя',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Отчество',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Дата рождения',
						kind: Kind.Date,
						drag: true,
						date: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Должность',
						kind: Kind.Text,
						man: true,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Руководитель',
						kind: Kind.Man,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Местный телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Домашний телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Факс',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Номер паспорта',
						kind: Kind.Text,
						drag: true,
						inp: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Паспорт выдан',
						kind: Kind.Text,
						drag: true,
						date: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Комната',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Сотовый телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'IP телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Значимость',
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Email',
						kind: Kind.Email,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Организация',
						kind: Kind.Org,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						drag: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Тип',
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
		],
	},
	{
		id: uid(),
		text: 'Цели',
		value: 'Цели',
		selected: false,
		level: 0,
		parent: [],
		children: [],
	},
	{
		id: uid(),
		text: 'Командировки',
		value: 'Командировки',
		selected: false,
		level: 0,
		parent: [],
		children: [],
	},
]

export { zero }
