import { uid } from 'quasar'

enum Kind {
	String,
	Text,
	Date,
	Org,
	Num,
	Man,
	Status,
	Link,
	Phone,
	Email,
	Bool,
}
const zero = [
	{
		id: uid(),
		text: 'Документы',
		selected: false,
		level: 0,
		parents: [],
		children: [
			{
				id: uid(),
				text: 'Исходящий',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Тема',
						kind: Kind.String,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Номер',
						kind: Kind.Num,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Регистратор',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Подготовил',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Содержание',
						kind: Kind.Text,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Согласующие',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Подписывают',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Получатели',
						kind: Kind.Org,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Исходящий', 'Получатели'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий', 'Получатели'],
								text: 'Организация',
								kind: Kind.Org,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий', 'Получатели'],
								text: 'Телефон',
								kind: Kind.Phone,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий', 'Получатели'],
								text: 'Email',
								kind: Kind.Email,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Состояние',
						kind: Kind.Status,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Заданиe',
						kind: Kind.Link,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Группа заданий',
						kind: Kind.Link,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
				],
			},
			{
				id: uid(),
				text: 'Входящий',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Тема',
						kind: Kind.String,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Номер',
						kind: Kind.Num,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Регистратор',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Содержание',
						kind: Kind.Text,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Исх.номер',
						kind: Kind.Num,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Дата документа',
						kind: Kind.Date,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Отправитель',
						kind: Kind.Org,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Входящий', 'Отправитель'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий', 'Отправитель'],
								text: 'Организация',
								kind: Kind.Org,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий', 'Отправитель'],
								text: 'Телефон',
								kind: Kind.Phone,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий', 'Отправитель'],
								text: 'Email',
								kind: Kind.Email,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Состояние',
						kind: Kind.Status,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Заданиe',
						kind: Kind.Link,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Группа заданий',
						kind: Kind.Link,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
				],
			},
			{
				id: uid(),
				text: 'Договор',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Номер',
						kind: Kind.Num,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Регистратор',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Подготовил',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Предмет договора',
						kind: Kind.Text,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Организация',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Дата документа',
						kind: Kind.Date,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Ответственный',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Подписывают',
						kind: Kind.Man,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Организация контрагент',
						kind: Kind.Org,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'Организация',
								kind: Kind.Org,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'Телефон',
								kind: Kind.Phone,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'Email',
								kind: Kind.Email,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'ИНН',
								kind: Kind.String,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'ОГРН',
								kind: Kind.String,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'БИК',
								kind: Kind.String,
								type: 1,
								level: 3,
								hidden: false,
								selected: false,
								drag: true,
								man: false,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Состояние',
						kind: Kind.Status,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Заданиe',
						kind: Kind.Link,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Группа заданий',
						kind: Kind.Link,
						type: 1,
						level: 2,
						hidden: false,
						selected: false,
						drag: true,
					},
				],
			},
			{
				id: uid(),
				text: 'Доп.соглашение',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [],
			},
		],
	},
	{
		id: uid(),
		text: 'Задания',
		selected: false,
		level: 0,
		parents: [],
		children: [
			{
				id: uid(),
				text: 'На исполнение',
				selected: false,
				parents: ['Задания'],
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'На ознакомление',
				selected: false,
				parents: ['Задания'],
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'На согласование',
				selected: false,
				parents: ['Задания'],
				level: 1,
				children: [],
			},
		],
	},
	{
		id: uid(),
		text: 'Группа заданий',
		selected: false,
		level: 0,
		parents: [],
		children: [
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Тема',
				kind: Kind.String,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
				inp: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Отправлено',
				kind: Kind.Date,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Срок исполнения',
				kind: Kind.Date,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Автор',
				kind: Kind.Man,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
				man: true,
				children: [
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Фамилия',
						kind: Kind.Text,
						man: true,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Имя',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Отчество',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Дата рождения',
						kind: Kind.Text,
						date: true,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Должность',
						kind: Kind.Text,
						drag: true,
						man: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Руководитель',
						kind: Kind.Man,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Местный телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Домашний телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Факс',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Номер паспорта',
						kind: Kind.Text,
						drag: true,
						inp: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Паспорт выдан',
						kind: Kind.Text,
						drag: true,
						date: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Комната',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Сотовый телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'IP телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Значимость',
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Email',
						kind: Kind.Email,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Организация',
						kind: Kind.Org,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						drag: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Содержание ',
				kind: Kind.Text,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
				inp: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Докумeнт',
				kind: Kind.Link,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Исполнители',
				kind: Kind.Man,
				man: true,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Состояние ',
				kind: Kind.Status,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Подчиненные задания',
				kind: Kind.Link,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Контролер',
				kind: Kind.Man,
				type: 1,
				level: 1,
				selected: false,
				drag: true,
				man: true,
				children: [
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Фамилия',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Имя',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Отчество',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Дата рождения',
						kind: Kind.Date,
						drag: true,
						date: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Должность',
						kind: Kind.Text,
						man: true,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Руководитель',
						kind: Kind.Man,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Местный телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Домашний телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Факс',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Номер паспорта',
						kind: Kind.Text,
						drag: true,
						inp: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Паспорт выдан',
						kind: Kind.Text,
						drag: true,
						date: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Комната',
						kind: Kind.Text,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Сотовый телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'IP телефон',
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Значимость',
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Email',
						kind: Kind.Email,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Организация',
						kind: Kind.Org,
						drag: true,
					},
					{
						type: 1,
						level: 2,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						drag: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Тип',
				type: 1,
				level: 1,
				selected: false,
				drag: true,
			},
		],
	},
	{
		id: uid(),
		text: 'Цели',
		selected: false,
		level: 0,
		parents: [],
		children: [],
	},
	{
		id: uid(),
		text: 'Командировки',
		selected: false,
		level: 0,
		parents: [],
		children: [],
	},
]

export { zero }
